apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: prcompany/gitopsfc
  newTag: 97e3ad4cc6936ef7da5891a88b6d144e0a9b3a81
